version: '3.9'

services:
  app-cv:
    build: ./admin
    image: cv-app:latest
    container_name: cv-application-container
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default
    depends_on:
      - postgresql
  postgresql:
    image: postgres:15.2
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=cv
      - POSTGRES_USER=cvuser
      - POSTGRES_PASSWORD=cvpass
    networks:
      - default
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

networks:
  default:
    name: cvnet
    driver: bridge

volumes:
  postgresql-data:
    name: pg-data
