spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cv
    username: cvuser
    password: cvpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    validate-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false
server:
  servlet:
    context-path: /api/v1
  port: 8090
