spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cv
    username: cvuser
    password: cvpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true